[package]
name = "advent-of-code-2025-rust"
version = "0.1.0"
edition = "2024"

[dependencies]

[[bin]]
name = "advent-of-code-2025-rust"
path = "main.rs"

[workspace]
members = [
    "day01",
    "day02",
    "day03"
, "day04", "day05"]
